Fix/quant test
kendryte/nncase pull request #1031
Opened 2023-08-01 06:13 UTC by Hejunchao6

2023-08-02 06:17 UTC, xhuohai requested changes

2023-08-02 06:17 UTC, xhuohai commented on tests/kernels/test_dequantize.cpp
> +        auto output1 = kernels::stackvm::dequantize(dt_float32, input.impl(),
自己跟自己比没有意义

2023-08-02 07:50 UTC, Hejunchao6 commented on tests/kernels/test_dequantize.cpp
> +        auto output1 = kernels::stackvm::dequantize(dt_float32, input.impl(),
done

2023-08-02 10:14 UTC, xhuohai commented
please bind jira ID with PR's title

2023-08-02 10:21 UTC, Hejunchao6 commented
> please bind jira ID with PR's title

done

2023-08-03 06:42 UTC, xhuohai approved these changes

2023-08-03 06:43 UTC, merged