Fix/kernel sqrt test
kendryte/nncase pull request #1082
Opened 2023-09-01 08:21 UTC by HeJunchao100813

2023-09-01 09:08 UTC, xhuohai requested changes

2023-09-01 09:08 UTC, xhuohai commented on tests/kernels/test_unary_sqrt.cpp
> +            std::uniform_int_distribution<> dis(0, 6);
建议范围搞大一点，rvv实现可能有近似算法，不同的范围的精度会不一样

2023-09-01 09:51 UTC, HeJunchao100813 commented on tests/kernels/test_unary_sqrt.cpp
> +            std::uniform_int_distribution<> dis(0, 6);
done

2023-09-06 07:00 UTC, xhuohai approved these changes

2023-09-06 07:01 UTC, merged