Fix/cos nan
kendryte/nncase pull request #1090
Opened 2023-09-13 05:44 UTC by HeJunchao100813

2023-09-13 06:57 UTC, xhuohai requested changes

2023-09-13 06:57 UTC, xhuohai commented on tests/compare_util.py
> +    if np.isnan(pred).any():
这里不太合适吧，万一gt和pred有相同个数的nan但是位置不一样，后面比较不就错位了？
应该获取gt的nan的位置，然后gt和pred都remove这些位置再比较？

2023-09-13 07:39 UTC, HeJunchao100813 commented on tests/compare_util.py
> +    if np.isnan(pred).any():
done

2023-10-16 06:47 UTC, xhuohai approved these changes

2023-10-16 06:47 UTC, merged