add mse
kendryte/nncase pull request #1110
Opened 2023-10-20 08:42 UTC by HeJunchao100813

2023-10-23 02:53 UTC, xhuohai requested changes

2023-10-23 02:53 UTC, xhuohai commented on tests/compare_util.py
> +        return -1 if math.isnan(result) or mse(gt, pred) >= 1 else result
>=1 may be too strict or not enough, for example gt=0.8, pred=0.4, mse=0.16.

2023-10-23 02:57 UTC, HeJunchao100813 commented on tests/compare_util.py
> +        return -1 if math.isnan(result) or mse(gt, pred) >= 1 else result
Revise it 0.01

2023-10-24 04:07 UTC, xhuohai approved these changes

2023-10-24 05:25 UTC, merged