GNNE-1714:Fix/regression bugs
kendryte/nncase pull request #1117
Opened 2023-10-31 06:22 UTC by uranus0515

1, Implement ConvTranspose to avoid OrtKi bugs;
2, Avoid null name caused by reference types;

2023-11-01 10:20 UTC, FusionBolt commented on src/Nncase.Evaluator/NN/Conv2DTranspose.cs
> +                var w_group_p = weights.ToArray<float>().AsSpan().Slice((int)g * (int)g_oc * (int)g_ic * (int)kernelShape[2] * (int)kernelShape[3]);
ToArray should be called outside the loop.

2023-11-01 10:20 UTC, FusionBolt commented on src/Nncase.Evaluator/NN/Conv2DTranspose.cs
> +                                in_v = input.ToArray<float>()[inputIndex];
same as above

2023-11-01 10:21 UTC, FusionBolt commented on src/Nncase.Evaluator/NN/Conv2DTranspose.cs
> +            outCache[i] = outCache[i] + bias.ToArray<float>()[biasIdx];
same as above

2023-11-01 10:22 UTC, FusionBolt requested changes
ToArray should be called outside the loop. Otherwise it will be very slow.

2023-11-01 11:06 UTC, xhuohai requested changes

2023-11-01 11:06 UTC, xhuohai commented on src/Nncase.Evaluator/NN/Conv2DTranspose.cs
> +        var g_ic = inputShape[1] / groups;
camel case is better

2023-11-02 03:20 UTC, xhuohai approved these changes

2023-11-02 03:25 UTC, FusionBolt approved these changes

2023-11-02 03:27 UTC, merged