relu6 support
kendryte/nncase pull request #756
Opened 2023-01-03 07:14 UTC by aaltonenzhang

relu6 marker and eval

2023-01-03 08:12 UTC, zhen8838 reviewed
Please add rewrite test case in UnitTestEGraphRewriteFactory.cs/UnitTestDataFlowRewrite.cs

2023-01-03 08:12 UTC, FusionBolt requested changes

2023-01-03 08:12 UTC, FusionBolt commented on src/Nncase.Tests/Quant/UnitTestAddRangeOfMarker.cs
> +    public void TestAddRangeOfMarkerToRelu6()
The test code body is almost the same for each marker, the common parts need to be extracted

2023-01-04 02:36 UTC, FusionBolt approved these changes

2023-01-04 03:01 UTC, merged