add LayerNorm
kendryte/nncase pull request #825
Opened 2023-03-02 11:48 UTC by Hejunchao6

2023-03-09 11:53 UTC, xhuohai requested changes

2023-03-09 11:53 UTC, xhuohai commented on src/Nncase.Tests/Evaluator/UnitTestEvaluatorNN.cs
> +        // Assert.Equal(expect, expr.Evaluate().AsTensor());
need to open test

2023-03-09 11:53 UTC, xhuohai commented on src/Nncase.Transform/Rules/Neutral/FoldLayerNorm.cs
> +namespace Nncase.Transform.Rules.Neutral;
need to add test for each pattern

2023-03-13 02:31 UTC, Hejunchao6 commented
add layer_norm&&fold_layer_norm

2023-03-13 03:36 UTC, xhuohai requested changes

2023-03-13 03:36 UTC, xhuohai commented on src/Native/src/kernels/stackvm/reference/layernorm.cpp
> + *
conflict with layer_norm.cpp

2023-03-13 03:36 UTC, xhuohai commented on src/Nncase.Tests/Evaluator/UnitTestEvaluatorNN.cs
> +    {
need to test more parameters, especially axis

2023-03-13 11:44 UTC, xhuohai requested changes

2023-03-13 11:44 UTC, xhuohai commented on src/Nncase.Tests/Evaluator/UnitTestEvaluatorNN.cs
> +                var axis = i;
negative axis is missing

2023-03-13 13:00 UTC, merged